title: Clase de Tecnologías de la Información
logo: /images/escudo.jpg
description: Clase de Tecnologias de la Información en la Universidad Panamericana
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
